### PR TITLE
setHealth fix

### PR DESCRIPTION
**Pull request by PEMapModder**
Replaces #12

### CODE REVIEW

**Comment by xxFlare** [comment]
:+1:

**Comment by PEMapModder** [comment]
@tntloverlol mind explaining?

**Comment by tntloverlol** [comment]
@PEMapModder Katana is a server software meant for power users, they shouldn't be setting invalid values for health anyway. I don't like the idea of introducing tons of failsafes throughout the API for plugins sending bad data, would junk up the code and not help.

**Comment by PEMapModder** [comment]
@tntloverlol there is nothing wrong with it.

This issue came to my attention because of subsequent calls from heal and attack. Before calling these functions, the final damage is unknown.

PocketMine itself sometimes exceeds the values as well.

**Pull request closed without merging**
