### PR TITLE
Some fixes,

### PR DESCRIPTION
**Pull request by xxFlare**

### CODE REVIEW

**Comment by Gamecrafter** [comment]
@xxFlare You shouldn't name call this a "fix". It should be called a "punctuation improvement".

**Comment by KnownUnown** [comment]
@Gamecrafter, it's fine. It's already been done, and it doesn't really matter. Focus on the larger things, and not the small things - if you want details to obsess over, go write a plugin ;)

**Comment by Gamecrafter** [comment]
@KnownUnown Hehehe, I'm a perfectionist. :stuck_out_tongue:

**Comment by PEMapModder** [comment]
@Gamecrafter "typo fix", ok?

**Pull request closed without merging**
