### PR TITLE
Disabled movement checks.

### PR DESCRIPTION
**Pull request by xxFlare**
Removes movement check, useful for game servers.

### CODE REVIEW

**Comment by shoghicp** [comment]
This allows everyone to hack and noclip :)

**Comment by Gamecrafter** [comment]
@xxFlare You want people using hacks and stuff? :stuck_out_tongue:

**Comment by xxFlare** [comment]
@Gamecrafter This will be re-added later, but as an option rather then default.

The code here makes many players mad as they get teleported back, but not everyone wants this disabled.

**Comment by Gamecrafter** [comment]
@xxFlare I think it'll make even more players mad when they see other players using hacks, and knowingly no way to prevent it.

**Comment by xxFlare** [comment]
@Gamecrafter Like I said, it's going to be re-added as an option.

Anti-Fly hacks still work with this disabled, collision checks get off.

**Comment by Gamecrafter** [comment]
@xxFlare I know, I kinda like the idea of being able to toggle movement checks. I get super mad when I move and it gets reverted.

**Pull request closed without merging**
