### PR TITLE
Create PlayerFoodLevelChangeEvent

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by KnownUnown** [comment]
Invalid - class name is "PlayerChatEvent". Additionally, the implementation is quite poor, there is no methods or variables that allow you to get the food level, completely nullifying the purpose of the event itself. Additionally, please use an IDE - your indentation is messed up.

**Comment by Creeperface01** [comment]
how can i use IDE? i can't fork forked repository and i dont know about another way

**Comment by Creeperface01** [comment]
i tried clone it and create pull request from github app but it didn't work

**Comment by KnownUnown** [comment]
Clone your repo locally, then push to the remote. Then go into the GitHub web interface, diff the two repos, and create a pull request.

**Pull request closed without merging**
